# TAG:entity_type # Different company types. Example: BC, A, C, etc. BC Registries registeres different types of organizations, Example: Corporations, Sole Proprietorships, Societies, Co-ops, etc.
select topic.source_id, topic.type, cred.entity_type from (select distinct on (credential_json->'attributes'->>'entity_type') corp_num, create_timestamp, credential_json->'attributes'->>'entity_type' entity_type, credential_json->'attributes'->>'entity_name' entity_name from hookable_cred where credential_type = 'registration.registries.ca' order by credential_json->'attributes'->>'entity_type', id desc) as cred, topic where topic.source_id = cred.corp_num;
# TAG:entity_status # ACTive and/or HIStorical companies. BC Registries tracks a more detailed company status, but we just publish the summary active or historical status.
select topic.source_id, topic.type, cred.entity_status from (select distinct on (credential_json->'attributes'->>'entity_status') corp_num, create_timestamp, credential_json->'attributes'->>'entity_status' entity_status, credential_json->'attributes'->>'entity_name' entity_name from hookable_cred where credential_type = 'registration.registries.ca' order by credential_json->'attributes'->>'entity_status', id desc) as cred, topic where topic.source_id = cred.corp_num;
# TAG:entity_name_assumed # BC and Extra-provincial companies (name, assumed name, home and remote jurisdiction, i.e "entity_name", "assumed_name", "home_jurisdiction", "registered_jurisdiction"). Extra-provincial companies (registered outside of BC) may use an "assumed name" in BC if their registered name is not available.
select topic.source_id, topic.type, cred.home_jurisdiction, cred.registered_jurisdiction from (select distinct on (credential_json->'attributes'->>'home_jurisdiction', credential_json->'attributes'->>'registered_jurisdiction') corp_num, create_timestamp, credential_json->'attributes'->>'home_jurisdiction' home_jurisdiction, credential_json->'attributes'->>'registered_jurisdiction' registered_jurisdiction, credential_json->'attributes'->>'entity_name' entity_name from hookable_cred where credential_type = 'registration.registries.ca' order by credential_json->'attributes'->>'home_jurisdiction', credential_json->'attributes'->>'registered_jurisdiction', id desc) as cred, topic where topic.source_id = cred.corp_num;
# TAG:topic_relationship # Sole Proprietorships (FM), DBA and Owned-by companies. We publish relationship credentials for Sole Proprietorships that are wholly owned by Corporations.
select topic.source_id, topic.type, cred.relationship, cred.associated_registration_id from (select distinct on (credential_json->'attributes'->>'relationship') corp_num, create_timestamp, credential_json->'attributes'->>'relationship' relationship, credential_json->'attributes'->>'associated_registration_id' associated_registration_id from hookable_cred where credential_type = 'relationship.registries.ca' order by credential_json->'attributes'->>'relationship', id desc) as cred, topic where topic.source_id = cred.corp_num;
# TAG:topic_relationship # Sample with a large number of relationships. Example: Telus, Pattison.
select source_id, type, id from topic where id in (select topic_id from (select topic_id, count(*) count from topic_relationship group by topic_id order by count desc limit 5) as foo);
# TAG:credential # We re-publish a credential whenever a company name, status, or any other attribute changes, this can lead to a large number of credentials.
select source_id, type, id from topic where id in (select topic_id from (select topic_id, count(*) count from credential where credential_type_id = 1 group by topic_id order by count desc limit 5) as foo);
# TAG:credential_type # Other credentials. Example: BN, Cannabis license.
select source_id, type, id from topic where id in (select topic_id from (select distinct on (credential_type_id) topic_id from credential order by credential_type_id) as foo);
